.PHONY: help init test start docs

SHELL := /bin/bash

# Load .env if present
ifneq (,$(wildcard ./.env))
include .env
export
endif

OXID_URL ?=
OXID_API_KEY ?=

help:
	@echo ""
	@echo "  OxidDB starter kit"
	@echo ""
	@echo "  make init     Create .env by entering your instance URL and API key"
	@echo "  make test     Check that your OxidDB instance is online and reachable"
	@echo "  make start    Open an interactive feasibility session for your idea"
	@echo "  make docs     List the documentation versions bundled in ./docs"
	@echo ""

# ---------------------------------------------------------------------------
# make init: prompt for instance details and write .env
# ---------------------------------------------------------------------------
init:
	@if [ -f .env ]; then \
		read -r -p ".env already exists. Overwrite? [y/N] " answer; \
		case "$$answer" in [yY]*) ;; *) echo "Keeping existing .env."; exit 0;; esac; \
	fi; \
	read -r -p "OxidDB instance URL (e.g. https://your-instance-id.oxid-db.com): " url; \
	url="$${url%/}"; \
	if [ -z "$$url" ]; then echo "Instance URL is required."; exit 1; fi; \
	read -r -p "API token for your instance: " key; \
	printf '# Generated by make init. See .env.example for what each value means.\nOXID_URL=%s\nOXID_API_KEY=%s\n' \
		"$$url" "$$key" > .env; \
	echo "Wrote .env for $$url. Run 'make test' to verify the connection."

# ---------------------------------------------------------------------------
# make test: mechanical health check against the provisioned instance
# ---------------------------------------------------------------------------
test:
	@if [ ! -f .env ]; then \
		echo "No .env found. Run 'make init' to create one."; \
		exit 1; \
	fi
	@if [ -z "$(OXID_URL)" ]; then \
		echo "OXID_URL is not set in .env"; \
		exit 1; \
	fi
	@echo "Pinging $(OXID_URL) ..."
	@status=$$(curl -s -o /tmp/oxid_health.json -w "%{http_code}" \
		--max-time 10 \
		-H "Authorization: Bearer $(OXID_API_KEY)" \
		"$(OXID_URL)/health"); \
	if [ "$$status" = "200" ]; then \
		echo "Instance is up."; \
		cat /tmp/oxid_health.json; \
		echo ""; \
	elif [ "$$status" = "401" ] || [ "$$status" = "403" ]; then \
		echo "Reached the instance but the API key was rejected (HTTP $$status)."; \
		exit 1; \
	elif [ "$$status" = "000" ]; then \
		echo "Could not reach $(OXID_URL). Check the URL, your network, or whether the instance is still provisioning."; \
		exit 1; \
	else \
		echo "Instance responded with HTTP $$status."; \
		cat /tmp/oxid_health.json 2>/dev/null; \
		exit 1; \
	fi

# ---------------------------------------------------------------------------
# make start: hand the feasibility prompt to Claude Code and go interactive
# ---------------------------------------------------------------------------
start:
	@command -v claude >/dev/null 2>&1 || { \
		echo "Claude Code is not installed or not on your PATH."; \
		echo "Install it, then run 'make start' again."; \
		exit 1; \
	}
	@if [ ! -f FEASIBILITY.md ]; then \
		echo "FEASIBILITY.md is missing. It carries the interview prompt."; \
		exit 1; \
	fi
	@if [ ! -d docs ]; then \
		echo "Warning: no ./docs folder found. The session will have no capability reference to check against."; \
	fi
	@echo "Starting an OxidDB feasibility session. Describe your idea when asked."
	@echo ""
	@claude "$$(cat FEASIBILITY.md)"

docs:
	@if [ -d docs ]; then \
		echo "Documentation versions available:"; \
		ls -1 docs; \
	else \
		echo "No ./docs folder found."; \
	fi
